services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env        # Django получит все переменные
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - backend/.env        # Postgres возьмёт только POSTGRES_* и ему норм
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg_data: